project:
  type: website
  output-dir: docs

website:
  title: "Cálculo del volumen"
  navbar:
    left:
      - href: index.qmd
        text: Inicio

format:
  html:
    theme: cosmo
    toc: true
    math: mathjax
